# Test your FastAPI endpoints

POST http://127.0.0.1:8083/api/rank
Accept: application/json
Content-Type: application/json

{"question": "What is a banana?", "documents": ["A banana is a fruit", "A Carrot is a vegetable", "A Pizza is a food dish"]}
###
